name: Sekret-Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'sekret.properties'
      - 'app/sekret/*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Sekret
        run: ./gradlew app:createNativeLib