name: Unix-Build

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create package on Ubuntu
        run: ./gradlew app:packageAppImage

      - name: Compress package
        run: tar czf AppImage.tar.gz build/release/main/app/eSports-Prodigy

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: AppImage.tar.gz
          retention-days: 1